<link rel="stylesheet" href="/TCC/css/nav.css" type="text/css"/>
<nav class="navbar navbar-expand-lg navbar-dark layout text-white fixed-top w-100" shadow-lg>
  <a class="navbar-brand titulo" href="#">Parque Vivo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
        <ul class="nav nav-pills nav-fill">
            <li class="nav-item px-2">
                <a class="nav-link link" href="pg_inicial.php"><span class="glyphicon glyphicon-home"></span> Home</a>
            </li>
            <li class="nav-item px-2">
                <a class="nav-link link" href="mensagem_adm.php"><span class="glyphicon glyphicon-comment"></span>  MENSAGENS</a>
            </li>
            <li class="nav-item px-2">
               <a class="nav-link link" href="evento_cadastrados.php"><span class="glyphicon glyphicon glyphicon glyphicon-list-alt"></span>  EVENTOS CADASTRADOS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link link" href="deslogar.php"><span class="glyphicon glyphicon-share"></span>  SAIR</a>
            </li>
        </ul>
    </div>
</nav>
